# Site settings
title: Lexus Escapes
client:
  name: Lexus
  link: "https://ad.doubleclick.net/ddm/clk/425812537;227655136;j"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Discover unforgettable road trips and start planning your next adventure. Head out on the road with Lexus and Secret Escapes, with gorgeous British stays set to inspire your getaway. Watch the Hiles family embark on their very own road trip, before browsing our bespoke road trip guides and luxurious hotel offers.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/lexus-escapes" # the subpath of your site, e.g. /blog/
img:     "/lexus-escapes/_assets/img"
css:     "/lexus-escapes/_assets/css"
js:      "/lexus-escapes/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed